-- Migration number: 0001 	 2025-09-06T09:25:49.788Z
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	hash BLOB NOT NULL,
	gender INTEGER NOT NULL,
	access_level INTEGER NOT NULL DEFAULT 100,
	is_verified INTEGER NOT NULL DEFAULT 0,
	created_on INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
);
